server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux: # ĐÂY LÀ CHỖ CẮM CHUẨN MỚI
          routes:

            # 2. Định tuyến cho dịch vụ Sản phẩm (Product)
            - id: product-route
              uri: lb://product-service
              order: 2
              predicates:
                - Path=/api/v1/products/**

            # 3. Định tuyến cho dịch vụ Đơn hàng (Order)
            - id: order-route
              uri: lb://order-service
              order: 3
              predicates:
                - Path=/api/v1/orders/**

      # --- CẤU HÌNH HẠ TẦNG (Discovery) ---
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

# 🔑 Cấu hình JWT (Dùng để filter hoặc trích xuất thông tin nếu cần)
jwt:
  secret: "ShopeeSieuBaoMatChuanMicroservice2026"

eureka:
  client:
    serviceUrl:
      # TRONG DOCKER: Phải dùng tên container 'discovery-server' thay vì 'localhost'
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "gateway,health,info"

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG