server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Sửa từ http://discovery-server... thành localhost
    register-with-eureka: false
    fetch-registry: false